### PR TITLE
Fix elapsed time when game is paused

### LINKED ISSUE #264: Time elapsed with problem again (someone ignored the fix!)
## Description
#221 fixed the problem with the time elapsed when the game was paused. This fix paused the timer when the game was paused. However, the `develop` branch doesn't have this change anymore. This means that someone made a mistake while accepting PRs and the problem returned.

## Steps to Reproduce
1. Go to #221 and see the changes that were made
2. Go to the `develop` branch
3. Check the `void showscene()` function
4. Compare both codes (the changes were unmade)

## What should happen?
Time elapsed should be paused when the game is paused.

## Relevant screenshots
Changes made in #221:
image

Current code status:
image

@Tyago-Teoi can you do the changes you did to time elapsed one more time? Otherwise, I could replicate what you did in #221 ...

### PR DESCRIPTION
**Pull request by yuji-teoi**
Fixes #264  .

Now the elapsed time is paused while the user is in the pause menu, after the player press 'p' on the gameplay scene.

### CODE REVIEW

File: src/ttsnake.c [hunk 1]
```diff
@@ -291,10 +292,17 @@ void showscene (scene_t* scene, int scene_type, int menu) {
 
 	switch (scene_type) {
 		case RUNNING:
-		case PAUSED:
 			/* Calculating elapsed time to display while the game is running. */
 			timeval_subtract(&elapsed_last, &before, &beginning);
 			timeval_subtract(&elapsed_total, &now, &beginning);
+
+			break;
```
Comment (yuji-teoi) [inline src/ttsnake.c:298]:
```suggestion
			break;
			
```

**Review by yuji-teoi — COMMENTED** [review]
just a breakline

File: src/ttsnake.c [hunk 2]
```diff
@@ -291,10 +292,18 @@ void showscene (scene_t* scene, int scene_type, int menu) {
 
 	switch (scene_type) {
 		case RUNNING:
-		case PAUSED:
 			/* Calculating elapsed time to display while the game is running. */
 			timeval_subtract(&elapsed_last, &before, &beginning);
 			timeval_subtract(&elapsed_total, &now, &beginning);
+
```
Comment (yuji-teoi) [inline src/ttsnake.c]:
```suggestion
```

**Review by yuji-teoi — COMMENTED** [review]
delete an adictional breakline

**Review by JBMolotov — APPROVED** [review]

**Comment by mvellosa** [comment]
good feature!

**Review by Haltz01 — APPROVED** [review]
Everything seems OK once again. This change is just like the previous one made in #221.
